---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS_DIR')}}"
    - TYPEORM_CONNECTION: "{{ lookup('ansible.builtin.env', 'TYPEORM_CONNECTION', default='postgres')}}"
    - os_environment:
        - key: TYPEORM_CONNECTION
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_CONNECTION')}}"
        - key: TYPEORM_ENTITIES
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_ENTITIES')}}"
        - key: TYPEORM_HOST
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_HOST')}}"
        - key: TYPEORM_PORT
          value: 5432
        - key: TYPEORM_USERNAME
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_USERNAME')}}"
        - key: TYPEORM_PASSWORD
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_PASSWORD')}}"
        - key: TYPEORM_DATABASE
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_DATABASE')}}"
        - key: TYPEORM_MIGRATIONS
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS')}}"
        - key: TYPEORM_MIGRATIONS_DIR
          value: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS_DIR')}}"

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      ansible.builtin.wait_for_connection:

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    TYPEORM_CONNECTION: "{{ lookup('ansible.builtin.env', 'TYPEORM_CONNECTION')}}"
    TYPEORM_ENTITIES: "{{ lookup('ansible.builtin.env', 'TYPEORM_ENTITIES')}}"
    TYPEORM_HOST: "{{ lookup('ansible.builtin.env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('ansible.builtin.env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('ansible.builtin.env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('ansible.builtin.env', 'TYPEORM_DATABASE')}}"
    TYPEORM_MIGRATIONS: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS_DIR')}}"

  roles:
    - configure-server
