---
- name: Create .prod.env file
  shell: |
    echo "TYPEORM_CONNECTION={{ lookup('ansible.builtin.env', 'TYPEORM_CONNECTION', allow_unsafe=True)}}" > .prod.env
    echo "TYPEORM_ENTITIES={{ lookup('ansible.builtin.env', 'TYPEORM_ENTITIES', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_HOST={{ lookup('ansible.builtin.env', 'TYPEORM_HOST', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_PORT=5432" >> .prod.env
    echo "TYPEORM_USERNAME={{ lookup('ansible.builtin.env', 'TYPEORM_USERNAME', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_PASSWORD={{ lookup('ansible.builtin.env', 'TYPEORM_PASSWORD', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_DATABASE={{ lookup('ansible.builtin.env', 'TYPEORM_DATABASE', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_MIGRATIONS={{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS', allow_unsafe=True)}}" >> .prod.env
    echo "TYPEORM_MIGRATIONS_DIR={{ lookup('ansible.builtin.env', 'TYPEORM_MIGRATIONS_DIR', allow_unsafe=True)}}" >> .prod.env

- name: "update apt"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: true
  shell: n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
