- name: Copy backend files
  register: copyBackend
  copy:
    src: ../../artifact.tar.gz
    dest: ~/

- name: Extract the zipped artifact
  register: extract
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ~/
    remote_src: yes

- name: Start server
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
