- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy backend files
  register: copyBackend
  copy:
    src: ../../artifact.tar.gz
    dest: ~/

- name: Extract the zipped artifact
  register: extract
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend
    remote_src: yes

- name: Remove zip after extracting
  ansible.builtin.file:
    path: ~/artifact.tar.gz
    state: absent

- name: Start server
  shell: |
    cd ~/backend
    sudo mv .prod.env ~/backend/.env
    npm install
    pm2 stop default
    pm2 start npm -- start
